### ISSUE TITLE
Show total test time in tester results

### ISSUE THREAD

**Issue by Gert-dev** [yacut/tester#16]
Hello

It would be neat if the total time it took to run the tests would be displayed in the tester results. The time for the individual tests is already displayed, which is really handy.

I understand that the time the process or provider takes to finish may not be representative (i.e. if the provider or process does more work before and after the tests), but perhaps a simple sum of all individual test time values would be more correct?

Thanks in advance

**Comment by Gert-dev** [comment]
Thanks for adding this. It may be interesting to round the time to 2 digits after the dot, since now it can show something like `5.901000000000112ms` :-).

**Comment by yacut** [comment]
Tester is just sum and showing what the providers sent. What provider are you using? The Problem for Jest was fixed in 1.1.6 release.

**Comment by Gert-dev** [comment]
I'm using tester-phpunit. What you're saying could be right: the duration of the tests themselves also have a lot of floating point digits, but it was less apparant there as there are actually tests which take 0.0047 seconds.

I think I also found another issue, potentially with tester-phpunit, I'm not sure: the time I'm seeing from tester-phpunit is the time in seconds, whilst this package always mentions `ms` to indicate milliseconds. This happens for the total test time as well as the time for the individual tests. For example, My total test time is around 6 seconds, yet I see 6.098044ms (which should either be 6.098044s or 6098.044 ms).

Perhaps it would be worthwile to show the totel test time in seconds, but the tests themselves in milliseconds? This because tests themselves can be very fast, but the total suite time for large suites can add up easily and could show very large numbers.

**Comment by Gert-dev** [comment]
Thanks for providing a fix. I'm still getting weird results, though, perhaps it is related to how tester-phpunit or PHPUnit is sending the data: I'm now always getting a total test time of 0.01 second and the duration column seems to be showing me fractions of seconds, even though the suffix says it contains milliseconds:

![test](https://user-images.githubusercontent.com/24809863/27494503-755ceaae-584e-11e7-95f0-e1cf6e34c169.png)

(Ignore the green crosses, I was experimenting with the styling.)

The actual duration of the total suite time is around 5 - 6 seconds, whilst `testConstantImport` takes around 9 milliseconds (0.009 seconds) rather than 0.009 milliseconds. (Also, perhaps the suffix `ms` could be shown once in the header, i.e. `Duration (ms)` instead of in every row separately.)
